"""
Magic Mirror OS - Unified Core Engine (Hybrid AI Edition)
=========================================================
Runs Hand Tracking and AI Face Recognition.
Integrates with the 8-Step Jupyter Notebook Brain.
"""

import cv2
import time
import threading
import pyautogui
import mediapipe as mp
import numpy as np
import pickle
import joblib
from mediapipe.tasks import python
from mediapipe.tasks.python import vision
from http.server import HTTPServer
from pathlib import Path

# Import logic from our existing files
import hand_tracker as ht
import face_recognition_system as fr

# Path to the model generated by the 8-Step Notebook
MODEL_PATH = Path("face_profiles/hybrid_ai_model.pkl")

def main():
    print("═══════════════════════════════════════════════════════")
    print("  MAGIC MIRROR OS : HYBRID AI CORE ENGINE (8-STEP)     ")
    print("═══════════════════════════════════════════════════════")

    # 1. Start Local Profile API (Port 8080)
    try:
        server = HTTPServer(('127.0.0.1', 8080), fr.FaceAPIHandler)
        threading.Thread(target=server.serve_forever, daemon=True).start()
        print("[✓] Automated Face-Login API running on Port 8080")
    except OSError:
        pass
        
    # 2. Setup AI Face Recognition
    profiles = fr.load_profiles()
    
    # Load the Notebook's Trained Brain
    model = None
    if MODEL_PATH.exists():
        try:
            model = joblib.load(MODEL_PATH)
            print("[✓] AI Brain Loaded from Notebook (SVM/PCA)")
        except Exception as e:
            print(f"[!] Warning: Could not load notebook model: {e}")
    else:
        print("[!] Warning: hybrid_ai_model.pkl not found. RUN YOUR NOTEBOOK FIRST!")
    
    # 3. Open Camera
    cap = cv2.VideoCapture(0)
    if not cap.isOpened():
        print("Error: Could not open camera.")
        return
    
    w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
    h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
    
    detector, recognizer = fr.get_ai_tools(w, h)
    if detector is None:
        print("[!] ERROR: AI Models (yunet/sface) missing.")
        return

    # 4. Setup Hand Tracker
    ht.download_model()
    base_options = python.BaseOptions(model_asset_path=ht.MODEL_PATH)
    options = vision.HandLandmarkerOptions(
        base_options=base_options,
        num_hands=1,
        min_hand_detection_confidence=0.6,
        min_hand_presence_confidence=0.6,
        min_tracking_confidence=0.6,
    )
    hand_detector = vision.HandLandmarker.create_from_options(options)
    print("[✓] Hand Tracking Engine Armed")

    # Configuration
    HAND_TIMEOUT = 2.0  
    last_hand_seen = time.time()
    frame_idx = 0
    prev_x, prev_y = 0, 0
    gesture_state = ht.GestureState.OPEN
    fist_start_time = 0.0
    last_click_time = 0.0
    mouse_held = False
    cached_face_results = []
    
    while True:
        success, image = cap.read()
        if not success: continue

        image = cv2.flip(image, 1)
        frame_idx += 1

        # Module A: Face Recognition (Every 10 frames)
        if frame_idx % 10 == 0:
            cached_face_results = []
            _, faces = detector.detect(image)
            
            if faces is not None and model is not None:
                for face in faces:
                    coords = face[:4].astype(int)
                    face_aligned = recognizer.alignCrop(image, face)
                    current_embedding = recognizer.feature(face_aligned).flatten().reshape(1, -1)
                    
                    try:
                        # Use the 8-Step Notebook's Brain
                        probs = model.predict_proba(current_embedding)[0]
                        best_idx = np.argmax(probs)
                        best_score = probs[best_idx]
                        best_id = model.classes_[best_idx]
                        
                        if best_score > 0.60:
                            label = profiles["id_to_name"].get(int(best_id), "Unknown")
                            color = (0, 255, 0)
                            fr.SHARED_STATE["user"] = label
                            fr.SHARED_STATE["last_seen"] = time.time()
                        else:
                            label = "Unknown"
                            color = (0, 0, 255)
                        
                        cached_face_results.append((coords[0], coords[1], coords[2], coords[3], label, best_score, color))
                    except: pass
            elif faces is not None:
                for face in faces:
                    coords = face[:4].astype(int)
                    cached_face_results.append((coords[0], coords[1], coords[2], coords[3], "Train Notebook First", 0, (0, 0, 255)))

        # Draw Face UI
        for (fx, fy, fw, fh, label, conf, color) in cached_face_results:
            cv2.rectangle(image, (fx, fy), (fx+fw, fy+fh), color, 2)
            cv2.putText(image, f"{label} ({int(conf*100)}%)", (fx, fy-10), 0, 0.7, color, 2)

        # Module B: Hand Tracking
        image_rgb = cv2.cvtColor(image, cv2.COLOR_BGR2RGB)
        mp_image = mp.Image(image_format=mp.ImageFormat.SRGB, data=image_rgb)
        try:
            results = hand_detector.detect(mp_image)
            if results.hand_landmarks:
                lm = results.hand_landmarks[0]
                px, py = ht.hand_center(lm)
                hx, hy = px * w, py * h
                
                # Screen mapping
                x_mapped = int((hx - ht.FRAME_R) / (w - 2 * ht.FRAME_R) * ht.SCREEN_W)
                y_mapped = int((hy - ht.FRAME_R) / (h - 2 * ht.FRAME_R) * ht.SCREEN_H)
                x_mapped = max(0, min(ht.SCREEN_W - 1, x_mapped))
                y_mapped = max(0, min(ht.SCREEN_H - 1, y_mapped))
                
                curr_x = prev_x + (x_mapped - prev_x) / ht.SMOOTHING
                curr_y = prev_y + (y_mapped - prev_y) / ht.SMOOTHING
                pyautogui.moveTo(int(curr_x), int(curr_y))
                prev_x, prev_y = curr_x, curr_y
                last_hand_seen = time.time()
                
                cv2.circle(image, (int(hx), int(hy)), 10, (0, 255, 80), -1)
                
                # Gestures
                fist_now = ht.is_fist(lm)
                if fist_now and gesture_state == ht.GestureState.OPEN:
                    gesture_state = ht.GestureState.CLOSED
                    fist_start_time = time.time()
                elif not fist_now and gesture_state == ht.GestureState.CLOSED:
                    if mouse_held:
                        pyautogui.mouseUp()
                        mouse_held = False
                    elif (time.time() - fist_start_time) < ht.HOLD_THRESHOLD:
                        pyautogui.click()
                    gesture_state = ht.GestureState.OPEN
                elif fist_now and gesture_state == ht.GestureState.CLOSED:
                    if (time.time() - fist_start_time) >= ht.HOLD_THRESHOLD and not mouse_held:
                        pyautogui.mouseDown()
                        mouse_held = True
        except: pass

        # UI Overlay
        api_user = fr.SHARED_STATE["user"]
        api_status = f"LOGGED IN: {api_user}" if api_user else "AWAITING FACE (AI)..."
        cv2.putText(image, api_status, (20, 40), cv2.FONT_HERSHEY_SIMPLEX, 0.7, (255, 255, 255), 2)

        cv2.imshow("Magic Mirror OS : AI Master Engine", image)
        if cv2.waitKey(1) & 0xFF == ord('q'): break

    cap.release()
    cv2.destroyAllWindows()

if __name__ == "__main__":
    main()
